### ISSUE TITLE
How can I build a custom launcher?

### ISSUE THREAD

**Issue by xbhive** [zenith110/ToontownServer#15]
In the [build folder](/zenith110/ToontownServer/tree/41936c594351f2db0057ab3008045e85f5b18935/build), there's a **build.py** file which does not appear to be build the launcher correctly.

**Tried with**: All/separate/no arguments, same issue.
**OS Version**: Windows Server 2012 (x64)
**Python**: Panda3D v1.10.0

```
C:\ToontownServer\build>%ppython% make.py --compile-cxx
Traceback (most recent call last):
  File "make.py", line 9, in <module>
    from niraitools import *
  File "nirai/src\niraitools.py", line 1, in <module>
    assert not __debug__ # Run with -OO
AssertionError
```

If commented out (with #), I am them told that AES is not installed.

```
C:\ToontownServer\build>%ppython% make.py
Traceback (most recent call last):
  File "make.py", line 9, in <module>
    from niraitools import *
  File "nirai/src\niraitools.py", line 9, in <module>
    import aes
ImportError: No module named aes
```

This also does not seem to be embedded with Panda.
```
C:\ToontownServer\build>%ppython% -m pip install aes
C:\Panda3D-1.10.0\python\ppython.exe: No module named pip

C:\ToontownServer\build>%ppython% -m p install aes
C:\Panda3D-1.10.0\python\ppython.exe: No module named p
```

**Comment by zenith110** [comment]
Hi, the code for the launcher is in source code. I have a .exe in the releases for you to look at if you prefer that. Thank you.

**Comment by xbhive** [comment]
Thanks @zenith110 Ill try this now.
When you have time can you please check the email I sent you thank you.

**Comment by xbhive** [comment]
Issue Fixed we where able to open the launcher and connect using it thank you @zenith110

**Comment by xbhive** [comment]
This launcher does appear to work, however would it be possible to run this through command line arguments (eg. launcher.exe"playcookie" "server") ? This would be be helpful to integrate the launcher into a custom launcher (which is already designed to get a Username/IP.

**Comment by xbhive** [comment]
Hey @zenith110 

Was wondering if you where able to look into this issue as my team and I are in the process of production.

**Comment by zenith110** [comment]
If you wish to add more features, the source code of the launcher is provided in the source code folder. This launcher is meant to be for small servers(mostly friends), and if you wish to deviate from that intended purpose, you will have to modify the source code itself. 

I can assist on helping you locate the specific files, but you will have to add your intended features. If you wish to add more to the gui itself, you will need to open the .ui files using qtdesigner, and recompile using pyside2-uic. I hope this solves your inquiry, let me know if you need more information.

**Comment by xbhive** [comment]
After editing the UI, I tried to open the **launcher.py** which says I don't have the **PySide2** module.
This version of Python doesn't seem to have a copy of PIP, so I can install the module.
How could I manually install this module, so that the file could be run?

```
Traceback (most recent call last):                                                                                                          
  File "ToontownServer-master\sourceCode\launcher.py", line 8, in <module>                                                                                                                   
    from PySide2 import QtWidgets, QtCore, QtGui                                                                                            
ModuleNotFoundError: No module named 'PySide2'                                                                                                                                                                                           
```

**Comment by xbhive** [comment]
Hoping to get your help to be able to fix this issue as I cant seem to build it because of me getting this error as sated above @zenith110 if you can connect to my team viewer or anydesk I would like to ask if you can help me with this please via remote desktop connection.

**Comment by zenith110** [comment]
You will need to pip install PySide2, I use python 3 for these files. Let me know if you need more help.

**Comment by zenith110** [comment]
You will also need to move the launcher.py to the root directory of the server files as they're reliant on the paths to function, unless you wish to change them.

**Comment by xbhive** [comment]
@zenith110 I will try this now one sec

**Comment by xbhive** [comment]
I understand that the launcher needs to be in the root directory, however the PySide2 module still could not be found (if it was included already). How would I install PIP for the current version of Python that I am using?

**Comment by zenith110** [comment]
What version of python do you use? do you have python in your enviroment variables?

**Comment by xbhive** [comment]
Does it matter which version it is ? **&** Which version should I be using ?

Would like if you can connect via to my pc today if possible to help me set this up to at least build correctly do you have a fast way to contact can I send you an email ?

**Comment by xbhive** [comment]
**"What version of python do you use? do you have python in your environment variables?"**

1: ) The version of python we use is (  **v1.10**  ).
2: ) We ( dont   ) have python in our environment variables.

Can you please write on how to do this correctly ? or Can send me all this via dropbox or email with the correct launcher thats able to be built so we dont go back and forth with debugging if its worked on your end ?


Thank you @zenith110

**Comment by zenith110** [comment]
In regards to this, the version that I used to create this launcher is python3. You will need python3 and pip to install PySide2.  https://www.python.org/downloads/ is the link to download the latest version of python. Information about PySide2 can be found here: https://pypi.org/project/PySide2/ Hope this helps.

**Comment by xbhive** [comment]
@zenith110 

we do know that we need to install this using pip. However we didnt seem to get this with our version of python that came with source you provided.

This is why im asking if you can connect to my vps via anydesk to take a look.

**Comment by xbhive** [comment]
Hey @zenith110 

**I've been online refreshing this page waiting on a reply all day** 

I'm asking if you can connect to my vps to help with this problem because I've tried everything unless your able to include this in the source above other then that us texting back and forth about this is going know where with what we really need help with.

**You have the solution to this problem.**

Adding these things to the source with detailed instructions would actually make this source one of the only sources out there that actually has a launcher that builds for the source.

**Comment by zenith110** [comment]
Okay, send me an email and we'll work it out there.

**Comment by xbhive** [comment]
Ok thank you @zenith110 I will contact you now via the email that you have on your website.

**Comment by xbhive** [comment]
@zenith110 I have sent you a message via using LinkedIn all info to log into the vps has been sent you able to login and download what’s needed.

I would hope you can get everything working properly on the vps for the launcher to build properly.
