### ISSUE TITLE
How to fix and enable some things..

### ISSUE THREAD

**Issue by xbhive** [zenith110/ToontownServer#17]
Im here to ask if you can help me with the following:

1) **What is the default access level number for a regular user ?**

2) **How  can I change it so that each user that logs in wont always be a system admin ?**

3) **How do you keep names from auto approving after logout ?**

**Comment by zenith110** [comment]
If you wish to assign access levels, you will have to set up a database and modify/create a config file of access and store it on the database. This will also help with the names, as there is not a system set up to let you manually review.
