### ISSUE TITLE
Sent you an Email - Important 

### ISSUE THREAD

**Issue by xbhive** [zenith110/ToontownServer#18]
Ive sent you an email from two emails please view them as soon as you can as ive taken two days off work starting tomorrow for me to be home and wait for your response since its hard to talk back and forth.

https://i.imgur.com/G7RtrRu.png

**Comment by xbhive** [comment]
We can delete this issue after..

**Comment by zenith110** [comment]
Hi there, unfortunately I've been busy as of late. I had just been able to come online and check out this issue. I'll look at it tomorrow as I have some issues to take care of.

**Comment by xbhive** [comment]
Ok thats ok if you can pick an email to reply back from the emails ive sent we can chat on there as ill have the vps ready for you.

**Comment by xbhive** [comment]
ive sent all the info needed in the email for you to connect via remote connection.
